### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by herlon214** [Wikiki/bulma-tooltip#1]
Can you write something about compatibily in the README? I'll help guys so much.

Thanks in advance.

**Comment by Wikiki** [comment]
Hi,

I'll do, I'm in holidays now but I'll do it when I'll be back.

Regards

**Comment by herlon214** [comment]
Nice! 
If you need any help I'm here.

**Comment by Wikiki** [comment]
Hi @herlon214,

Thanks for your proposal. If you want to do it, you can create a PR. I'll be glad to have your help on it.

Rehards
