### ISSUE TITLE
Tooltip is spinning if button is displaying loading animation

### ISSUE THREAD

**Issue by RealAtix** [Wikiki/bulma-tooltip#10]
Hi,

If a button has both `is-loading` and `tooltip` classes the tooltip will replace the loading animation and spin.

![Image of issue](https://i.imgur.com/o0sxXVW.gif)

**Comment by Wikiki** [comment]
Hi @RealAtix,

I didn't tried with loading modifier. It seems we both use ::after.
I'll see how to handle that

**Comment by jartaud** [comment]
Anything on this?

**Comment by Wikiki** [comment]
Not yet.
I'm working on it.

**Comment by Wikiki** [comment]
Hi @jartaud,

I just commit a fisrt level of correction.
Now <code>is-loading</code> modifier still working.
But when the button is in loading state the tooltip is not displayed anymore. I work on it to see if we can have both: loading state + tooltip together.

**Comment by Wikiki** [comment]
Unfortunately due to the use of <code>pointer-events: none</code> by Bulma to made the button in a disabled state (not clickable). We are loosing the <code>hover</code> event too and then the tooltip can't be displayed in a loading mode.

**Comment by jartaud** [comment]
@Wikiki Thanks!
