### ISSUE TITLE
Adding .is-tooltip-active

### ISSUE THREAD

**Issue by alfonsogarciacaro** [Wikiki/bulma-tooltip#11]
In some cases it could be interesting to display the tooltip all the time not only on hovering. For that we could add/remove a `is-tooltip-active` class programmatically as with other Bulma elements. [I already did that](https://github.com/alfonsogarciacaro/bulma-tooltip/commit/43d4831393ff62bd8f41de42dcb94cb18319f758) and it's working. Would you be interested in a PR?

Thanks a lot for the awesome Bulma extensions! :clap: :clap:

**Comment by Wikiki** [comment]
Hi @alfonsogarciacaro,

don't hesitate to create a PR for this.
