### ISSUE TITLE
Suggestion: Responsive Positioning

### ISSUE THREAD

**Issue by nixklai** [Wikiki/bulma-tooltip#13]
I am currently using tooltip in navbar to show some information. I set the position to show at the left, which works fine when it is in "desktop" mode but not in "touch" mode.

**In desktop**
<img width="387" alt="In desktop mode" src="https://user-images.githubusercontent.com/9111262/35767992-89d3d64e-0930-11e8-928e-a8e096284c32.png">

**In touch**
<img width="148" alt="In touch mode" src="https://user-images.githubusercontent.com/9111262/35767997-92625042-0930-11e8-83a5-df3ab6e490fa.png">

Would you consider adding responsive support, like "`.is-tooltip-right-when-is-mobile`" and "`.is-tooltip-top-when-is-touch`"?

**Comment by nixklai** [comment]
Sorry for my late response.
I am trying to use tooltip inside the navbar. Since I would like to have it on the right, [it will overflow](https://jsfiddle.net/nicklai/468y95k0/embedded/result/) when 
1. the tooltip is on the right in desktop devices, and 
2. the tooltip is on the left in touch devices.

### Workaround 1: Javascript
My workaround is to use JavaScript to detect the screen size and alter the class accordingly, like [this](https://jsfiddle.net/nicklai/e2fn9pr4/9/embedded/result/).

### Workaround 2: CSS
Another method I can think of is to inherit `.is-tooltip-right` with the Bulma `touch` mixin, but I cannot use `@extend` for inheriting so it has plenty repetition.
```
    @include touch {
        .is-tooltip-right-when-is-mobile:after{
            /*** From .is-tooltip-right:after ***/
            top: auto;
            bottom: 50%;
            left: 100%;
            right: auto;
            transform: translate(-1rem, 50%);
        }
        .is-tooltip-right-when-is-mobile:hover:before {
            /*** From .is-tooltip-right:hover:before ***/
            top: 50%;
            left: 100%;
            right: auto;
            border-color: transparent rgba($tooltip-background-color, 0.9) transparent transparent;
        }
        .is-tooltip-right-when-is-mobile:hover:after {
            /*** From .is-tooltip-right:hover:after ***/
            top: auto;
            bottom: 50%;
            left: 100%;
            right: auto;
            transform: translate(0.5rem, 50%);
        }
    }
```

I would like to see if it is possible to add some classes to support responsive design with a more elegant and tidy solution.

**Comment by Wikiki** [comment]
your approach using <code>is-tooltip-mobile-right</code> classes seems to be a good idea.
Don't hesitate to propose a PR to include those modifiers

**Comment by turbopixel** [comment]
Same problem here. Testet on my ipad and OnePlus X.

**Comment by Wikiki** [comment]
Hi,

I still don't understand how you can trigger a <code>:hover</code> on a touch device.

**Comment by turbopixel** [comment]
On touch devices, the tooltip is executed when an element is tapped. It is even enough to add the tooltip on a <span> tag and tap on it. 

That's crazy, but unfortunately true.
