### ISSUE TITLE
Broken with version 1.0.3

### ISSUE THREAD

**Issue by amir20** [Wikiki/bulma-tooltip#18]
Ever since updating to version 1.0.3, everything seems to be broken. Here are some screenshots: 

<img width="454" alt="screen shot 2018-02-22 at 7 37 33 am" src="https://user-images.githubusercontent.com/260667/36547737-66ea8e3a-17a3-11e8-8160-d8c3777c61e6.png">
<img width="362" alt="screen shot 2018-02-22 at 7 37 41 am" src="https://user-images.githubusercontent.com/260667/36547738-6716d954-17a3-11e8-8a2f-a7b0308f3335.png">

I haven't investigated much because I don't have that much CSS except bulma and and tooltip. I looked at the CSS and it looks like all fine to me. I am a little stumped.

**Comment by Wikiki** [comment]
Hi,

Can you please share the code you use ?

**Comment by amir20** [comment]
I have two: 

First screenshot is: 

```html
<p class="heading is-tooltip-right tooltip is-tooltip-multiline" data-tooltip="{{ tooltip }}">
            {{ label }}
            <span class="icon is-small">
                <i class="fas fa-info-circle"></i>
            </span>
        </p>
```

Second screenshot is 

```html
<h5 class="title is-5 is-tooltip-right tooltip is-tooltip-multiline" data-tooltip="Similar clans are based on clan activity and progress in the last 24 hours.">
                        Similar Clans
                        <span class="icon">
                            <i class="fas fa-info-circle"></i>
                        </span>
                    </h5>
```

**Comment by amir20** [comment]
By the way, I am currently on version `1.0.1`. Updating to latest causes this.

**Comment by Wikiki** [comment]
I don't see what's broken !?
The last modificaiton was to only invert content of ::before and ::after css rules to be able to work with <code>is-loading state</code> on button

**Comment by amir20** [comment]
There is a lot of changes since version 1.0.1 https://github.com/Wikiki/bulma-tooltip/compare/7a223a17dc53f8c281fbf73e787b8ac913f55489...master I can keep looking when I get a chance.

**Comment by Wikiki** [comment]
Those changes are related to the is-loading mode. As mentioned: inverting ::before and ::after css rules.

Again, I don't see what's not working on your screenshots ?

**Comment by amir20** [comment]
You don't see the arrow on the left side of the tooltip completely broken? 

<img width="453" alt="screen shot 2018-02-22 at 7 56 39 am" src="https://user-images.githubusercontent.com/260667/36548743-ee7bca60-17a5-11e8-860a-2c2d07f7abab.png">

**Comment by Wikiki** [comment]
Ho yes ;-)

Do you have some codepen.io to share so I'll be able to have a look on this issue ?

**Comment by amir20** [comment]
I am going to clear my cache and reinstall on npm modules. If it doesn't work then I will work on a codepen example. It's going to take a while as I have a lot of dynamic code generating with webpack so i'll have to figure out how to bring that over.

**Comment by Wikiki** [comment]
Ok. Good luck.

Please keep me in touch.

**Comment by amir20** [comment]
I think I figured out the issue. I wasn't easily able to create the codepen. But once I did, I was able to compare why it worked. During that process, I ended up removing all my imports until it broke again. The culprit is `@import "~buefy/src/scss/buefy";` so buefy seems to have its tooltip and this module has conflicting classes.  Unfortunately, I rely on buefy too much to remove it. I don't even use the tooltip but there is no way to just include some components. This must have happened after your refactor because `:after` has changed a little. 

I currently don't have a solution for this and will remain on 1.0.1 for a while. 

Can you think of a way to fix this on my side?

**Comment by Wikiki** [comment]
Good to know.
Why don't use sass file and prefix mu extension with a custom name ?

**Comment by amir20** [comment]
Yea, something like this https://www.ryadel.com/en/css-namespaces-avoid-conflict-style-sheets-files/ ? 

I am going to try it now.

**Comment by amir20** [comment]
I am struggling because when I do:

```css
.has-tooltip {
  @import "~bulma-tooltip";
}

.has-buefy {
  @import "~buefy/src/scss/buefy";
}
```

it works but it breaks all my icons. buefy relies on bulma for some cascading rules and they all seem broken. I need to take a break and try again later.

**Comment by amir20** [comment]
I finally selectively imported what I wanted. 

```css
@import "~buefy/src/scss/utils/_all";
@import "~buefy/src/scss/components/_autocomplete";
@import "~buefy/src/scss/components/_dropdown";
@import "~buefy/src/scss/components/_form";
@import "~buefy/src/scss/components/_icon";
@import "~buefy/src/scss/components/_loading";
@import "~buefy/src/scss/components/_message";
@import "~buefy/src/scss/components/_notices";
@import "~buefy/src/scss/components/_panel";
@import "~buefy/src/scss/components/_select";
@import "~buefy/src/scss/components/_table";
@import "~buefy/src/scss/components/_tag";
```
