### ISSUE TITLE
Multiline problem with few text

### ISSUE THREAD

**Issue by Piero87** [Wikiki/bulma-tooltip#20]
Hi,
If the text in the tooltip is only of few words, the size of the tooltip is too large, there is a way to fit it to text size?
![schermata 2018-03-01 alle 09 57 01](https://user-images.githubusercontent.com/768952/36835577-fecc225c-1d36-11e8-83fe-e88ccc48f9d6.png)

**Comment by Wikiki** [comment]
Hi,

sorry for the late answer.
Do you have a codepen.io to provide ? Because I don't have this issue on my side (neither on the demo page).
