### ISSUE TITLE
Arrow and tooltip separation

### ISSUE THREAD

**Issue by mikerockett** [Wikiki/bulma-tooltip#21]
Not sure how this can be solved, but it appears that at certain font sizes, the following happens:

![image](https://user-images.githubusercontent.com/4586280/39260569-328c4a64-48ba-11e8-9cf9-9e404d1a2b53.png)

The only thing I've been able to come up with is using, for example, `top: calc(100% + 1px)`, but this means the tooltip must be opaque for the cases where they don't separate (different font size) so there's no alpha overlap.

Also not sure if this is happening on non-retina devices; not able to test that at the moment.

Is this something that can be looked at?

Thanks 👍

**Comment by mikerockett** [comment]
I've solved this my swapping out references to `.5rem` as dividing my inherited font size of 15px is evidently going to create problems.

**Comment by Wikiki** [comment]
Hi,

can you please provide a codepen.io with the issue ? so I'll be able to have a look.

regards

**Comment by mikerockett** [comment]
Hi – how would a codepen help? Simply setting the body font size to 15px for example is what triggers this.

**Comment by Wikiki** [comment]
Thanks, I tought you had more modifications ;-). I'll try

**Comment by mikerockett** [comment]
Ah, right – no modifications on my side, just using the classes as-is. 🙂

**Comment by Botanistt** [comment]
Well I am having the same problem. This behaviour is even noticeable on bulma extension site.
Here is a screnshot https://u.wam.lv/00.41.26-31.07.18.png This can be seen if your browser zoom is set to 90%. I thought this could be fixed if I moved the arrow just a bit higher, but seems that it is not possible. It is either going to overlap with the tooltip, or the space is going to be noticeable.

**Comment by tomerf-sndbox** [comment]
+1 no updates?

**Comment by Wikiki** [comment]
No, sorry. I did not had time to work on this (last calendar release kept me quiet busy).
I'll have a look on it in the following days.

**Comment by bodograumann** [comment]
The problem lies with how the arrow is created. The relevant style uses `border-width: 0.5rem`. Unfortunately the border width is then rounded to an integer. So if rounding-down occurs, there is a gap.

We should probably use two quarters of the border, rotate by 45° and move the center of `::after` to the left boundary of `::before`.

**Comment by Wikiki** [comment]
Fix coming in the next release

**Comment by datermine** [comment]
Which release is this in? I'm still seeing it in `bulma-tooltip/master/dist/css/bulma-tooltip.min.css`

In action:
![image](https://user-images.githubusercontent.com/286251/75055502-1f509a80-54a3-11ea-9ed2-1210439490be.png)

The markup is standard. I'm using `data-tooltip="..."` and the class `has-tooltip-left`
