### ISSUE TITLE
Tooltips are narrow with version 1.0.5

### ISSUE THREAD

**Issue by amir20** [Wikiki/bulma-tooltip#22]
I just updated to `1.0.5` and all my tooltips are narrower. I went to the demo and it is also doing that. 

<img width="413" alt="screen shot 2018-05-12 at 9 39 43 am" src="https://user-images.githubusercontent.com/260667/39959593-9158d114-55c8-11e8-8354-6dc9e955b6a0.png">

**Comment by amir20** [comment]
Any update on this? Seems like it's still broken.

**Comment by amir20** [comment]
@Wikiki ?

**Comment by allygraham** [comment]
The minimum width has been removed.

```
.tooltip.is-tooltip-multiline::before {
  min-width: 24rem; 
}
```
Put the above snippet in your CSS/SCSS to fix it.

**Comment by Wikiki** [comment]
Hi,

thanks @allygraham.
I'm looking for a way to get a better width without having to force the min-width property. But I didn't find any today.
