### ISSUE TITLE
Module build failed: Syntax Error

### ISSUE THREAD

**Issue by Observablerxjs** [Wikiki/bulma-tooltip#24]
I face an issue when trying to integrate bulma-tooltip, I followed the documentation and installed bulma, bulma-extensions and bulma-tooltip with npm. Then when I add this to my main css file and then build the project, I get the error:

![capture](https://user-images.githubusercontent.com/23528812/41415967-cd8b2ee4-6fb7-11e8-93d7-8cb6b0948e01.PNG)

**Comment by Wikiki** [comment]
please try last release

**Comment by Observablerxjs** [comment]
I installed the latest release `1.0.5`

**Comment by Wikiki** [comment]
1.0.5 is not the last one. A new one has been released today (v2.0.0)

**Comment by Observablerxjs** [comment]
Ok it's working now :+1: thank you for the help.
