### ISSUE TITLE
Error compiling tooltip.sass to .css

### ISSUE THREAD

**Issue by willmenn** [Wikiki/bulma-tooltip#3]
I tried to compile the `.sass` to `.css` and I receive this error:

```
sass tooltip.sass tooltip.css
Error: Undefined variable: "$radius".
        on line 5 of tooltip.sass
  Use --trace for backtrace.
```
I executed:
`sass tooltip.sass tooltip.css`.

- Sass version: `Sass 3.5.1 (Bleeding Edge)`

Could you help me? @Wikiki

**Comment by Wikiki** [comment]
Hi @willmenn,

You can't compile it alone. It has to be including in bulma.
Please see https://wikiki.github.io/bulma-extensions/overview

Regards

**Comment by willmenn** [comment]
Thank you @Wikiki !
