### ISSUE TITLE
tooltip is not working for new DOM elements (SVG)

### ISSUE THREAD

**Issue by jaguarxii** [Wikiki/bulma-tooltip#32]
I am creating DOM elements after "document.ready()" (svg elements), I assigned the "tooltip" class and "data-tooltip" properties, but it does not show.

Do you have any advice?

Best regards

![image](https://user-images.githubusercontent.com/8013436/45060657-8cc9fa80-b066-11e8-89ac-af6f1d0cf091.png)

Update 2018-09-22: here a sample:
https://jsfiddle.net/jaguarito/260d1cms/30/

**Comment by Wikiki** [comment]
Hi,

sorry but <code>:before</code> and <code>:after</code> do not currently work on SVG elements. So tooltip won't work on SVG.
