### ISSUE TITLE
tooltips don't work with bulma tabs

### ISSUE THREAD

**Issue by acidjazz** [Wikiki/bulma-tooltip#33]
example:

https://codepen.io/acidjazz/pen/MqPOPm?editors=1000

**Comment by Wikiki** [comment]
Arf, this is due to the <code>overflow: hidden</code>, <code>overflow-x: auto</code> rules set to the <code>.tabs</code> element.

**Comment by acidjazz** [comment]
@Wikiki i tried turning off the hidden and auto, and i still don't see them coming up, do you think there's any kind of work-around for this?

**Comment by michael-andreuzza** [comment]
Having the same problem.

**Comment by michael-andreuzza** [comment]
Has anyone found how to solve this?

**Comment by acidjazz** [comment]
@michael-andreuzza yea i basically just avoided tabs and made my own using button groups and some tweaking

**Comment by michael-andreuzza** [comment]
Ok, well, I guess I will have to do some work around too....thank you for answering @acidjazz .

Have a good day.

**Comment by Wikiki** [comment]
Hi,

unfortunately <code>tabs</code> component has <code>overflow: hidden;
overflow-x: auto;</code> css's rules which prevent tooltip to be displayed (they are outside the box). To make it work with tabs you have to add the following rule into your CSS:
```css
.tabs {
    overflow: visible !important;
}
```
