### ISSUE TITLE
Undefined variable: "$grey-dark". when importing into angular project

### ISSUE THREAD

**Issue by charsi** [Wikiki/bulma-tooltip#35]
Hi I tried importing 

`node_modules/bulma-extensions/bulma-tooltip/src/sass/index.sass`

and 

`node_modules/bulma-extensions/bulma-tooltip/dist/css/bulma-tooltip.sass`

by defining in angular.json which should compile it into the webpack build.

But I get an error instead --

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

$tooltip-background-color: $grey-dark !default
                          ^
      Undefined variable: "$grey-dark".

```

Importing just the css file in dist does not throw errors during build. But at run time I get the following error --
`Can't bind to 'tooltip' since it isn't a known property of 'button'. `

**Comment by Wikiki** [comment]
Hi,

Did you import bulma first ?

**Comment by charsi** [comment]
Yes I did

**Comment by Wikiki** [comment]
Weird: ```$grey-dark```is a bulma's core variable.
Czan you share your code with the import section flow so I'll be able to help you ?
