### ISSUE TITLE
.tooltip should be .has-tooltip

### ISSUE THREAD

**Issue by brunobuddy** [Wikiki/bulma-tooltip#36]
I tried to integrate this module on a project where we already had tooltips on SVG elements and I had to adapt the code. The reason is that the "tooltip" class was already used for other tooltips.

This happens because the element that has a tooltip is classed "tooltip" and I think it's a misconception. That element is not a tooltip but instead has one tooltip attached.

As Bulma used a lot of "has-something" CSS classes like "has-text-grey" or "has-background-white", it makes totally sense to convert that class into an "has-tooltip" to prevent amalgam it with its tooltip

**Comment by Wikiki** [comment]
Hi @brunobuddy,

You're right. I'll change into has-tooltip.

**Comment by Wikiki** [comment]
Coming in the next release
