### ISSUE TITLE
Only works on buttons

### ISSUE THREAD

**Issue by Silur** [Wikiki/bulma-tooltip#38]
Any plans on supporting other elements as well?

**Comment by Wikiki** [comment]
Hi,

tooltips are working on every element not only buttons.
For example:
```html
<span class="icon tooltip is-tooltip-right" data-tooltip="Tooltip example">
    <i class="fal fa-info-circle"></i>
</span>
```

**Comment by json-derulo** [comment]
There is a quirk for the mobile Safari. The tooltip won't open on click by default on span / div elements, only on buttons.
The solution is to put an empty onlick event on the element.
On other browsers, the tooltips should work though.

```
<span class="tooltip" data-tooltip="whatever" onclick="">My Tooltip</span>
```

See [this SO answer](https://stackoverflow.com/questions/8692072/jquery-click-event-of-a-div-in-li-element-not-fired-in-mobile-safari/8696213#8696213)
