### ISSUE TITLE
Tooltip's style is broken

### ISSUE THREAD

**Issue by rikusen0335** [Wikiki/bulma-tooltip#39]
Working on: yarn
Working with: Nuxt, Vue.js, Bulma(0.7.2)

I want to say is title, so it's now broken like below picture.
![snapcrab_noname_2019-1-7_3-0-8_no-00](https://user-images.githubusercontent.com/19174234/50739827-ace21400-1228-11e9-9104-d426c8336a61.png)

I have no idea how to fix, is this known bug? or is there anyway to fix this?

**Comment by steam0** [comment]
Any updates on this?

**Comment by rikusen0335** [comment]
Nothing commited. So not :(

**Comment by Wikiki** [comment]
No, sorry. I did not had time to work on this (last calendar release kept me quiet busy).
I'll have a look on it in the following days.

**Comment by steam0** [comment]
Any updates here?

**Comment by Wikiki** [comment]
Hi,

not yet sorry. I'm running out of time right now.
Any PR are welcome.

**Comment by rikusen0335** [comment]
@steam0 if you in a hurry and using Nuxt.js or Vue.js, use buefy's instead.
https://buefy.org/documentation/tooltip/

**Comment by Wikiki** [comment]
Fix is coming in the next release
