### ISSUE TITLE
Tooltip wrap around

### ISSUE THREAD

**Issue by fariasfrancisco** [Wikiki/bulma-tooltip#4]
I have a long text in a tooltip but the current max-width limits the displayed text and adds ellipsis. How can I make the text wrap around into a new line after it exceeds the max width?

**Comment by Wikiki** [comment]
Hi @fariasfrancisco ,

you can now use <code>is-tooltip-multiline</code> modifer to force multiline display.

Regards,

**Comment by fariasfrancisco** [comment]
Thanks a lot!
