### ISSUE TITLE
How to import from github (no npm)?

### ISSUE THREAD

**Issue by liagason** [Wikiki/bulma-tooltip#42]
Is there any documentation on how to install without npm?
I have imported bulma-extensions.min.js and bulma-tooltip.min.css but it does not seem to work.

**Comment by Wikiki** [comment]
Hi,

can you please share the part of code where you import files ?
You can use a tool like jsDelivr to import files from npm without using npm ;-)
<code>https://cdn.jsdelivr.net/npm/bulma-tooltip@2.0.2/dist/css/bulma-tooltip.min.css</code>

PS: tooltip extension has no javaScript yet. So you only have to import CSS file into your project (after importing Bulma CSS of course).

**Comment by liagason** [comment]
Thanks, probably I had downloaded the wrong file. I replaced it with the content of the file above and it now works.
