### ISSUE TITLE
Import problem

### ISSUE THREAD

**Issue by chimit** [Wikiki/bulma-tooltip#5]
After `npm install bulma-tooltip --save` can't import this package as
```
@import '~tooltip'
```
or
```
@import '~bulma-tooltip'
```

**Comment by Wikiki** [comment]
It should be fixed

**Comment by chimit** [comment]
Still doesn't work:
```
Module build failed: 
  @import '~tooltip';
^
      File to import not found or unreadable: ~tooltip.
Parent style sheet: stdin
```

**Comment by chimit** [comment]
@Wikiki, is [this line](https://github.com/Wikiki/bulma-tooltip/blob/3e885a610a32e678cf495da7cc9eb3414ee4d110/bulma-tooltip.sass#L3) needed? If I'm not mistaken this file doesn't exist in the bulma-tooltip folder.

I used bulma before found your module. So I already have `@import '~bulma';`

**Comment by Wikiki** [comment]
Hi,

the file <code>bulma-tooltip.sass</code> is only used by Travis CI.
The file to import is <code>tooltip</code>.

Have you tried using the full node_modules path ? <code>@import /node_modules/bulma-tooltip/tooltip</code>

Can you please confirm you're using the v0.0.5 ?

**Comment by chimit** [comment]
This works
```
@import '~bulma-tooltip/tooltip';
```
and this works as well:
```
@import '~bulma-tooltip';
```
But I'm curious because in the [guide](https://wikiki.github.io/) there is:
```
@import 'bulma'
@import 'checkradio'
```
not
```
@import 'bulma'
@import 'bulma-checkradio'
```
Is the guide wrong?

**Comment by Wikiki** [comment]
can you please tell me which version you're using ? I've made some changes yesterday on pckage.json so maybe I have to update the guide now.

**Comment by chimit** [comment]
Currently, I have `"bulma-tooltip": "^0.1.1",` in my package.json.

**Comment by Wikiki** [comment]
So the last update works.
Thanks
