### ISSUE TITLE
Only capital letters appear in tooltip

### ISSUE THREAD

**Issue by yh54321** [Wikiki/bulma-tooltip#51]
If a tooltip is used on a 'Material Design' icon, only capital letters are visible in the tooltip.
For instance in the following example, only the 'H' of 'Hello is visible:

 `          <i class="material-icons tooltip" data-tooltip="Hello">build</i>
`

![TooltipBug](https://user-images.githubusercontent.com/28165425/62021666-59b8ba00-b196-11e9-987c-28fb31651af9.png)

This is due to the 'Material Icons' font-family of the material-icons class. The tooltip likewise adopts this family, causing all lowercase letters to become invisible. I resolved this by adding the following to my css file:
`.material-icons.tooltip.is-tooltip-active::before,
.material-icons.tooltip:hover::before {
  font-family: auto;
}`

If somebody could propose an ideal solution it would be very helpful to users of icon libraries.

**Comment by Wikiki** [comment]
Fix coming in the next release
