### ISSUE TITLE
Documentation is / has 

### ISSUE THREAD

**Issue by Dreanad** [Wikiki/bulma-tooltip#57]
Hello !

I've been trying to get this tooltip working for an hour now

from https://wikiki.github.io/elements/tooltip/ 

in this documentation it is specified that the position of the tooltips is done by "is-tooltip-[placement]" 

but that's not true, when I looked in the file, I realized it was "has-tooltip-[placement]" 

Have a nice day

**Comment by Wikiki** [comment]
My bad. I forgot to update the documentation after the last release. I'll do it soon.

**Comment by Dreanad** [comment]
No problem ! great job by the way ! :)
