### ISSUE TITLE
v3.0.0 active tooltip

### ISSUE THREAD

**Issue by kerams** [Wikiki/bulma-tooltip#58]
Hi, `has-tooltip-active` does not seem to work in the latest version. The tooltip is still only displayed on hover. With 2.0.2 and `is-tooltip-active` it works as expected on the exact same element.

**Comment by Wikiki** [comment]
Hi,

try using <code>is-active</code>. the documentation will be updated soon. sorry.

**Comment by kerams** [comment]
Nope, neither that nor `is-tooltip-active`.

**Comment by Wikiki** [comment]
no: just <code>is-active</code>

**Comment by kerams** [comment]
Yeah, I've tried that too.

**Comment by Wikiki** [comment]
I'll have a look on it and let you inow.

**Comment by Wikiki** [comment]
The correct class modifier is <code>has-tooltip-active</code> and the issue has been fixed in v3.0.1

**Comment by kerams** [comment]
Thank you.
