### ISSUE TITLE
Right out of the gate, tooltip flickers

### ISSUE THREAD

**Issue by david-j-davis** [Wikiki/bulma-tooltip#8]
Hello, I installed via npm and have imported only the tooltip extension. Here is what Im seeing, flickering when hovering the tooltip. 
https://drive.google.com/open?id=1-GTa29Mz0zM2wURi9-tgvkoZB5ntJ51J

**Comment by david-j-davis** [comment]
Nevermind, closing this issue, but it turns out that if you place this tooltip on a fontawesome icon like `<i class="fa fa-clipboard tooltip" aria-hidden="true" data-tooltip="Copy to clipboard"></i>` it will flicker when hovering.

**Comment by Wikiki** [comment]
Hi,

I guess its because fontawesome and tooltip use ::after both. So it creates a conflict
