### ISSUE TITLE
tooltip.sass should imports initial variables

### ISSUE THREAD

**Issue by juanpmarin** [Wikiki/bulma-tooltip#9]
Hi, nice extension !
I'm having a problem with webpack dll because $grey-dark is not defined, I think the fix it's import the initial variables files, like this

`@import "~bulma/sass/utilities/initial-variables";`

**Comment by Wikiki** [comment]
Hi,

You should import bulma first. As detailed in the documentation.

Regards

**Comment by juanpmarin** [comment]
Yes, I did it, the thing is that webpack is trying to pre process your package directly

**Comment by Wikiki** [comment]
Maybe you could then import bulma-tooltip.sass instead of tooltip.sass

**Comment by juanpmarin** [comment]
I think I have not explained well, I'm gonna make a repo where the error is reproducible

**Comment by juanpmarin** [comment]
@Wikiki while doing the example repo I figured out that the fix it's exclude the bulma-tooltip package at the dllPlugin configuration, thanks a lot :D
